#include "wifi.h"
#include "esp_wifi_types.h"
#include "project_constants.h"

#include <stdbool.h>

#include "nvs_flash.h"
#include "esp_netif.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"

static const char *WIFI_TAG = "WIFI:";

// This function is responsible for managing the events generated by the
// wifi driver, all the logic is done here, not in the task that is respobsible
// only for configuring and starting up all the needed components.
static void wifi_event_handler(void* arg, esp_event_base_t event_base, int32_t event_id, void* event_data)
{
    int retry_attempts = 0;

    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_START) {
        ESP_LOGI(WIFI_TAG, "Succesfully started wifi station");
        esp_wifi_connect();
    }

    if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_CONNECTED) {

        ESP_LOGI(WIFI_TAG, "Succesfully connected to AP");
        retry_attempts = 0;
    }

    else if (event_base == WIFI_EVENT && event_id == WIFI_EVENT_STA_DISCONNECTED) {

        if (retry_attempts < WIFI_MAX_ATTEMPTS) {
            ESP_LOGI(WIFI_TAG, "Reconnecting to AP");
            esp_wifi_connect();
            retry_attempts++;
        }
        else {
            // Probably i should be doing something smarter than this
            ESP_LOGW(WIFI_TAG, "Failed to connect to AP");
        }

    }

    else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t* event = event_data;
        ESP_LOGI(WIFI_TAG, "got ip:" IPSTR, IP2STR(&event->ip_info.ip));

        ESP_LOGI(WIFI_TAG, "Starting MQTT module");
        // TODO:: start MQTT task
    }
}



// I want this task to initialize and start the wifi driver, register the
// wifi event handler
void wifi_init () {
    
    // These config steps are also used by the MQTT module.
    // Since the wifi needs to start before MQTT i execute them
    // directly here.
    // >>>>>>

    esp_err_t ret = nvs_flash_init();
    if (ret == ESP_ERR_NVS_NO_FREE_PAGES || ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
    ESP_ERROR_CHECK(nvs_flash_erase());
    ret = nvs_flash_init();
    }
    ESP_ERROR_CHECK(ret);

    ESP_ERROR_CHECK(esp_netif_init());

    ESP_ERROR_CHECK(esp_event_loop_create_default());

    // <<<<<<

    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    esp_event_handler_instance_t wifi_handler_instance;

    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        IP_EVENT, 
        IP_EVENT_STA_GOT_IP,
        &wifi_event_handler,
        NULL,
        &wifi_handler_instance
    ));

    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        WIFI_EVENT,
        ESP_EVENT_ANY_ID,
        &wifi_event_handler,
        NULL,
        &wifi_handler_instance
    ));

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA));

    wifi_config_t wifi_config = {
      .sta =
          {
              .ssid = WIFI_SSID,
              .password = WIFI_PASS,
          },
    };
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config));

    ESP_LOGI(WIFI_TAG, "Starting wifi driver");
    ESP_ERROR_CHECK(esp_wifi_start());
    // If successful generates an STA_START event, not managed by
    // the handler. Assuming it always successful

}
